"""Users path relationships

Revision ID: 3755574a28ab
Revises: a25dbab0cf5f
Create Date: 2020-10-28 16:20:19.883750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3755574a28ab'
down_revision = 'a25dbab0cf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('paths_completed',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_table('paths_completed')
    op.drop_table('followers')
    # ### end Alembic commands ###
